version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: test
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3307:3306"
    networks:
      - mynetwork

  app:
    image: node:16
    container_name: nuxt-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - mynetwork
    command: sh -c "npm install && npm run dev"

networks:
  mynetwork:
    driver: bridge
